### ISSUE TITLE
Option to automatically generate area and perimeter from geometry in `convert`?

### ISSUE THREAD

**Issue by cholmes** [fiboa/cli#38] opened 2024-05-06 03:17 UTC
When working with the converter I was thinking that area and perimeter should be pretty easy to calculate from the geometry.

It seems like you could potentially do them with geopandas, maybe fitting into the template? But it could also be nice to just have them be top-level 'convert' options, to just automatically add them based on the geometry.

See also - https://github.com/fiboa/specification/issues/28#issuecomment-2095121587 could be nice to have the validator check this as well.

**Comment by m-mohr** [comment] 2024-05-06 10:04
Duplicate of https://github.com/fiboa/cli/issues/21

**Closed** 2024-05-06 10:05 UTC
